#!/bin/bash
# By: Peter Talbott
# 09/06/2018; 04/10/2019, 6/6/2020

# Current Version
export VERSION=0.2

# Source function library.
source /lib/lsb/init-functions

if [ -f /usr/local/scripts/include/*.sh ]; then
  for INCLUDE_FILE in $(ls -1 /usr/local/scripts/include/*.sh); do
    . $INCLUDE_FILE
  done
fi

declare -ig ASTERIX=$((RANDOM))
declare -ig TAB=$((RANDOM))
declare -ig CR=$((RANDOM))
declare -ig ANDAND=$((RANDOM))
declare -ig RANDOM_MIN=$((1 + RANDOM % 15))
declare -ig INDEX=-1

export FILENAME="/etc/cron.d/unison-scripts_job"

# Define Global Arrays
declare -ag TEMPLATE_ARRAY=("## Autogenerated Cron File To Run UnisonServers.sh Version 0.1 Randomly" "$CR" \
  "## Do NOT Modify! This file will be overwritten!" "$CR" "$CR" "SHELL=/bin/sh" "$CR" "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" "$CR" "$CR" \
  "*/$((RANDOM_MIN))" "$ASTERIX" "$TAB" "$ASTERIX" "$ASTERIX" "$ASTERIX" "$TAB" "root" "$TAB" "/usr/local/sbin/UnisonServers.sh" \
  "--custom-folder=/usr/local/scripts" "--add-folder=/usr/local/etc" "--add-folder=/usr/local/sbin" "--add-folder=/home/pete/Documents" "--threshold=0"\
  "--prefer-remote" "--force-color" '|' 'tee' '/var/log/UnisonScripts.log' "$ANDAND" "/usr/local/sbin/GenCronUni.sh" "$CR");

for DATA in ${TEMPLATE_ARRAY[@]}; do
  ((INDEX++))
  if [ $INDEX -eq 0 ]; then printf "#" >$FILENAME; fi
  case $DATA in
    $TAB)
      printf "\t" >>$FILENAME
      ;;
    $CR)
      printf "\n" >>$FILENAME
      ;;
    $ASTERIX)
      printf "%s " '*' >>$FILENAME
      ;;
    $ANDAND)
      printf "%s " '&&' >>$FILENAME
      ;;
    *)
      printf "%s " $DATA >>$FILENAME
      ;;
  esac
done
