[1;32m[ 2020-08-08 @ 12:30 ] [0mUnisonServers.sh[1;34m	Version: [1;33m0.4.4[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mStart of Log: [1;33m[2020-08-08 @ 12:30:05 PM][0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mLocal Host Name: [1;33mbedroom-pc.gigaware.lan[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mRemote Host Name: [1;33mlxc.gigaware.lan[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mNumber of Running Unison Processess: [1;33m0[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mThreshold of Running Unison Processess: [1;33m0[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mLocal Folder List: [1;33m/usr/local/scripts /usr/local/etc /usr/local/sbin /home/pete/Documents[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mRemote Folder List: [1;33m/nfs/lxc.gigaware.lan/usr/local/scripts /nfs/lxc.gigaware.lan/usr/local/etc /nfs/lxc.gigaware.lan/usr/local/sbin /nfs/lxc.gigaware.lan/home/pete/Documents[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mUnison Options: [1;33m-auto -batch -times -numericids -rsync -killserver[0m
[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;32mLog File: [1;33m/var/log/unison/6-Server.log[0m

[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;34mExecuting: [1;33m/bin/unison /usr/local/scripts /nfs/lxc.gigaware.lan/usr/local/scripts -auto -batch -times -numericids -rsync -killserver -prefer /nfs/lxc.gigaware.lan/usr/local/scripts 	-ignore 'Name .cache*' -ignore 'Name plasmaConfSaver*' -ignore 'Name icons*' -logfile /var/log/unison/6-Server.log.INFO | tee -a /var/log/unison/6-Server.log
[1;32m[ 2020-08-08 @ 12:30 ] [0m
[0;36m| OpenWRT/OpenWRT.sh                    / backup/rarBackup/rarBackupROMsMD0.sh                                      / init/MountPoints-0.4.sh                         / init/init-UnisonDaemon-0.1.sh                               / init/init-xenWebSockify-0.1.sh                                - misc/ClearAptBtrfs.sh                       - misc/encode-0.2.sh                    - net     - setup/FixPHPMyAdmin.sh                        - source/test-xen.sh                    \ xen/LDAP-Client/auth-client-config-0.9ubuntu1/etc/auth-client-config                                                                      \ xen/LDAP-Client/auth-client-config...ad/profile_carriage_return/result                                                                        \ xen/LDAP-Client/auth-client-config...ient-config/profile.d/acc-default                                                                        \ xen/LDAP-Client/auth-client-config...ad/profile_missing_entries/result                                                                        | xen/LDAP-Client/auth-client-config...return/orig/pam.d/common-password                                                                        | xen/LDAP-Client/auth-client-config...e_begin/orig/pam.d/common-account                                                                        | xen/LDAP-Client/auth-client-config...fsm/S_1/orig/pam.d/common-account                                                                        | xen/LDAP-Client/auth-client-config...te_dbonly/orig/auth-client-config                                                                        | xen/LDAP-Client/auth-client-config-0.9ubuntu1/tests/fsm/S_6pau                                                                / xen/LDAP-Client/auth-client-config...ndb_dbonly/orig/pam.d/common-auth                                                                        / xen/LDAP-Client/auth-client-config...rofiles/orig/pam.d/common-session                                                                        / xen/leafpad/leafpad-0.8.18.1/config.h                                       / xen/leafpad/leafpad-0.8.18.1/po/he.gmo                                        - xen/leafpad/leafpad-0.8.18.1/src/.deps/leafpad-gtkprint.Po                                                            - xen/leafpad/leafpad-0.8.18.1/src/leafpad-search.o                                                   - misc/UnisonServers-0.3.sh                           changed  ---->            misc/GenCronUni-0.3.sh  
100%  00:00 ETA               100%  00:00 ETAFailed [misc/GenCronUni-0.3.sh]: The source file /usr/local/scripts/misc/GenCronUni-0.3.sh
has been modified during synchronization.  Transfer aborted.
               100%  00:00 ETA               [0m[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;33m/bin/unison[0;32m  * Success!
[0m

[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;34mExecuting: [1;33m/bin/unison /usr/local/etc /nfs/lxc.gigaware.lan/usr/local/etc -auto -batch -times -numericids -rsync -killserver -prefer /nfs/lxc.gigaware.lan/usr/local/scripts -prefer /nfs/lxc.gigaware.lan/usr/local/etc 	-ignore 'Name .cache*' -ignore 'Name plasmaConfSaver*' -ignore 'Name icons*' -logfile /var/log/unison/6-Server.log.INFO | tee -a /var/log/unison/6-Server.log
[1;32m[ 2020-08-08 @ 12:30 ] [0m
[0;36m- dhcp/dhcpd.global-0.2.conf.secondary                                      \ profile.d/sh.local                    \ sss/secrets/.secrets.mkey                           [0m[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;33m/bin/unison[0;32m  * Success!
[0m

[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;34mExecuting: [1;33m/bin/unison /usr/local/sbin /nfs/lxc.gigaware.lan/usr/local/sbin -auto -batch -times -numericids -rsync -killserver -prefer /nfs/lxc.gigaware.lan/usr/local/scripts -prefer /nfs/lxc.gigaware.lan/usr/local/etc -prefer /nfs/lxc.gigaware.lan/usr/local/sbin 	-ignore 'Name .cache*' -ignore 'Name plasmaConfSaver*' -ignore 'Name icons*' -logfile /var/log/unison/6-Server.log.INFO | tee -a /var/log/unison/6-Server.log
[1;32m[ 2020-08-08 @ 12:30 ] [0m
[0;36m\ DisAppProf.sh               | backup-ldap.sh                | init-resolv.0.1.sh                    | tapup.sh          [0m[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;33m/bin/unison[0;32m  * Success!
[0m

[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;34mExecuting: [1;33m/bin/unison /home/pete/Documents /nfs/lxc.gigaware.lan/home/pete/Documents -auto -batch -times -numericids -rsync -killserver -prefer /nfs/lxc.gigaware.lan/usr/local/scripts -prefer /nfs/lxc.gigaware.lan/usr/local/etc -prefer /nfs/lxc.gigaware.lan/usr/local/sbin -prefer /nfs/lxc.gigaware.lan/home/pete/Documents 	-ignore 'Name .cache*' -ignore 'Name plasmaConfSaver*' -ignore 'Name icons*' -logfile /var/log/unison/6-Server.log.INFO | tee -a /var/log/unison/6-Server.log
[1;32m[ 2020-08-08 @ 12:30 ] [0m
[0;36m| 1untitled.pdf               | ACTIVISION/Transformers/pcconfig.txt                                      / Associate Discounts_files/walmart_left_20130409.gif                                                     / Budget/xls/Budget Rev5 Excel Format.xls                                         / Child Support/2014/Dan Documents/C.../Clarke HS NY Progress Report.pdf                                                                        / Child Support/2018/PayStubs/Advanc...vance.2018.07.13.FL.CSE.eBook.pdf                                                                        - Child Support/2018/Scanned Documen...018-08-02.IWO.Wlmart.Lump.Sum.pdf                                                                        - Child Support/2018/Schedule/Schedule.Week.31.pdf                                                  - Credit One/2017-04.pdf                        - Karen/1-25-2010 to 2-8-2010/Origonals/8th Letter to Karen.odt                                                               \ Karen/2-9-2010 to 2-17-2010/Origonals/11th Letter to Karen.odt                                                                \ Lease/Page 4.pdf                  \ My Pictures/CraigsList/Car Parts/3-27-10/Mar27_0003.jpg                                                         \ My Pictures/CraigsList/Car Parts/350 4-Bolt Block/Mar20_0038.jpg                                                                  \ My Pictures/CraigsList/Computer Cables/May13_0005.jpg                                                       | My Pictures/First Winter 2009 in NY/25.jpg                                            | My Pictures/Linkin Park Concert 7-...66d89b94acebfd6a81d9c5da06ca1.jpg                                                                        | My Pictures/Linkin Park Concert 7-...aaa2441b4732fc794046249865c11.jpg                                                                        | Packages.gz             / Ray Document Pictures/Second/image5.png                                         / Scanned Documents/AM Water 06-2020.pdf                                        / Scanned Documents/WV_Stateleave.pdf                                     / Taxes/2017            / The Witcher/Chapter1/000028 - Haren's house-025.TheWitcherSave                                                                - ViberDownloads                - Witcher 2/gamesaves/AutoSave_0015.sav                                       - Witcher 2/gamesaves/ManualSave_0031.sav                                         - prescription              [0m[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;33m/bin/unison[0;32m  * Success!
[0m

[1;32m[ 2020-08-08 @ 12:30 ] [0m[1;33mFinal Outcome: [0;32m  * Success!
[0m