#! /bin/sh
# Simple script to launch under wine "Assassins Creed 1"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/Program Files/GOG.com/Assassins Creed"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine AssassinsCreed_Dx9.exe
cd /

xrandr -s 1366x768
return 0
