#! /bin/sh
# Simple script to launch under wine "Hitman 4 Blood Money"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/Program Files/Eidos/Hitman Blood Money"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine HitmanBloodMoney.exe
cd /

xrandr -s 1366x768
return 0
