#! /bin/sh
# Simple script to launch under wine "Hitman 2 Silent Assassin"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/GOG Games/Hitman 2 Silent Assassin"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine hitman2.exe
cd /

xrandr -s 1366x768
return 0
