#! /bin/sh
# Simple script to launch under wine "Hitman 3 Contracts"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/GOG Games/Hitman - Contracts"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine HitmanContracts.exe
cd /

xrandr -s 1366x768
return 0
