#! /bin/sh
# Simple script to launch under wine "Star Wars Knights of the Old Republic 2"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/GOG Games/Star Wars - KotOR2"
#WINEARCH=win32 WINEPREFIX=~/.wine32 force_s3tc_enable=true wine swkotor2.exe
WINEARCH=win32 WINEPREFIX=~/.wine32 wine swkotor2.exe
cd /

xrandr -s 1366x768
return 0
