#! /bin/sh
# Simple script to launch under wine "Star Wars: The Force Unleashed"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/Program Files/Aspyr/Star Wars The Force Unleashed"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine SWTFU.exe
cd /

xrandr -s 1366x768
return 0
