#! /bin/sh
# Simple script to launch under wine "The Witcher 2 Assassins of Kings Enhanced Edition"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/GOG Games/The Witcher 2 Enhanced Edition/bin"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine witcher2.exe -dontForceMinReqs
cd /

xrandr -s 1366x768
return 0
