#! /bin/sh
# Simple script to launch under wine "The Witcher 2 Assassins of Kings - User Content Manager"

sleep 2
export WINEDEBUG=-all

cd "/opt/usr/wine32/GOG Games/The Witcher 2 Enhanced Edition/bin"
WINEARCH=win32 WINEPREFIX=~/.wine32 wine userContentManager.exe
cd /

xrandr -s 1366x768
return 0
